#!/bin/bash

xsetroot -cursor_name left_ptr
sxhkd &

bspc config border_width	2
bspc config window_gap		0

bspc config split_ration	0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifer	mod1

bspc config automatic_scheme	spiral

bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on

$HOME/polybar-collection/launch.sh
