#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
        xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output DP-2 --mode 2560x1600 --left-of eDP-1 &
	polybar externalmain &
	polybar externalcetner &
	polybar externalright &
	bspc monitor DP-2 -d 1 2 3 4
	bspc monitor eDP-1 -d 5 6 7 8
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
fi

bspc config border_width         2
bspc config window_gap          25
bspc config top_padding		10
bspc config left_padding 	5
bspc config right_padding	5
bspc config bottom_padding	5
bspc config active_border_color "#303446"
bspc config normal_border_color "#BABBF1"
bspc config focused_border_color "#F4B8E4"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Startup 

#xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output DP-2 --mode 2560x1600 --left-of eDP-1
polybar main &
polybar center &
polybar right &
polybar externalmain &
polybar externalcenter &
polybar externalright &
picom --experimental-backends &
feh --bg-fill  ~/Documents/Wallpaper/cat-waves.png &
